---
title: "Final Project"
author: "jvogel, smillard, tsmith"
date: "2022-11-05"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
options(dplyr.summarise.inform = FALSE)
```

Getting dataset from R:

```{r}
dat<- esoph
```


First we model our data in order to check if the residuals are normally distributed in order to conduct ANOVA. Out model will be 



```{r}

model <- aov(dat$ncases ~ dat$agegp+dat$alcgp+dat$tobgp, data = dat)

#summary(model)

#plot the model
plot(model)

#looking at histogram of residuals
hist(model$residuals, main = "Residuals Histogram")


```
  


```{r}
shapiro.test(model$residuals)
```

uhh ohh looks like data is not normally distributed.

trying again but with probability 

```{r}
esoph$percentage <- esoph$ncases / (esoph$ncontrols+esoph$ncases)

model2 <- aov(percentage ~ agegp + tobgp + alcgp, data = esoph) #Linear model is created in order to apply anova test

plot(model2$residuals)
hist((model2$residuals))


#formal test of normality

shapiro.test(model2$residuals)

#here p-value >.05 so we would not reject the null as there is strong evidence against rejecting the null.


```






Game Plan


#number of cancer cases are normally distributed?







#two way anova/3 way anova

First lets try the two way anova:

```{r} 
#We need our dependent variable (percent of cancer cases) and two independent variables (I picked tobacco and alcohol use) in their own data set.
esoph.twoway <- esoph[ , c("alcgp", "tobgp", "percentage")]

#Next I generate a frequency table (not sure if this is 100% needed)
table(esoph.twoway$alcgp, esoph.twoway$tobgp)
#the table shows that we have a relatively balanced design (the guides words not mine)

#We create the anova test
esoph.aov2way <- aov(percentage ~ alcgp + tobgp, data = esoph.twoway)
#Then use summary to summarize the test
summary(esoph.aov2way)

#notes, I havent done any analysis on what the test shows, I also am not sure if we want to assume the variables interact at all
#the model above is called an additive model hence the + sign, but if we think the variables interact we can use an * instead of the +

```

```{r}
esoph.aov3way <- aov(percentage ~ alcgp + tobgp + agegp, data = esoph)

summary(esoph.aov3way)

```


#tukey's test

```{r}
TukeyHSD(esoph.aov3way, which = "alcgp" )
```
```{r}
TukeyHSD(esoph.aov3way, which = "agegp" )
```
